// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: ricartagrawala.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RAService_RequestCS_FullMethodName = "/ra.RAService/RequestCS"
	RAService_SendReply_FullMethodName = "/ra.RAService/SendReply"
)

// RAServiceClient is the client API for RAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -------------------------------
// Service
// -------------------------------
//
// We model the two message types as two unary RPCs.
// - RequestCS: peer asks us for permission; we may reply immediately or defer.
// - Reply: peer tells us we have permission (possibly after deferral).
//
// Why unary RPCs (not streams)?
//   - Simpler to reason about and test.
//   - gRPC preserves FIFO *per connection* (as long as we reuse one channel per peer),
//     which matches the algorithm’s FIFO channel assumption.
type RAServiceClient interface {
	// A peer asks for permission to enter the critical section.
	RequestCS(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
	// A peer grants permission (may be deferred and sent later).
	SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Empty, error)
}

type rAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRAServiceClient(cc grpc.ClientConnInterface) RAServiceClient {
	return &rAServiceClient{cc}
}

func (c *rAServiceClient) RequestCS(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RAService_RequestCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAServiceClient) SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RAService_SendReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAServiceServer is the server API for RAService service.
// All implementations must embed UnimplementedRAServiceServer
// for forward compatibility.
//
// -------------------------------
// Service
// -------------------------------
//
// We model the two message types as two unary RPCs.
// - RequestCS: peer asks us for permission; we may reply immediately or defer.
// - Reply: peer tells us we have permission (possibly after deferral).
//
// Why unary RPCs (not streams)?
//   - Simpler to reason about and test.
//   - gRPC preserves FIFO *per connection* (as long as we reuse one channel per peer),
//     which matches the algorithm’s FIFO channel assumption.
type RAServiceServer interface {
	// A peer asks for permission to enter the critical section.
	RequestCS(context.Context, *Request) (*Empty, error)
	// A peer grants permission (may be deferred and sent later).
	SendReply(context.Context, *Reply) (*Empty, error)
	mustEmbedUnimplementedRAServiceServer()
}

// UnimplementedRAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAServiceServer struct{}

func (UnimplementedRAServiceServer) RequestCS(context.Context, *Request) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCS not implemented")
}
func (UnimplementedRAServiceServer) SendReply(context.Context, *Reply) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedRAServiceServer) mustEmbedUnimplementedRAServiceServer() {}
func (UnimplementedRAServiceServer) testEmbeddedByValue()                   {}

// UnsafeRAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAServiceServer will
// result in compilation errors.
type UnsafeRAServiceServer interface {
	mustEmbedUnimplementedRAServiceServer()
}

func RegisterRAServiceServer(s grpc.ServiceRegistrar, srv RAServiceServer) {
	// If the following call pancis, it indicates UnimplementedRAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RAService_ServiceDesc, srv)
}

func _RAService_RequestCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServiceServer).RequestCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAService_RequestCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServiceServer).RequestCS(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAService_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServiceServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAService_SendReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServiceServer).SendReply(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

// RAService_ServiceDesc is the grpc.ServiceDesc for RAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ra.RAService",
	HandlerType: (*RAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCS",
			Handler:    _RAService_RequestCS_Handler,
		},
		{
			MethodName: "SendReply",
			Handler:    _RAService_SendReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ricartagrawala.proto",
}
