// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: ricartagrawala.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty = no payload (canonical for simple ACK-less RPCs).
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ricartagrawala_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ricartagrawala_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ricartagrawala_proto_rawDescGZIP(), []int{0}
}

// Request for critical section access.
// In Ricart–Agrawala, REQUEST carries the Lamport timestamp and sender ID.
// Priority is determined by (timestamp, from_id) with smaller being higher priority.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`        // Lamport logical clock value at send time
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"` // unique node ID (used as tie-breaker on equal timestamps)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_ricartagrawala_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_ricartagrawala_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_ricartagrawala_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Request) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

// Reply granting permission.
// In Ricart–Agrawala, a REPLY means "you have my permission right now".
// We still include a timestamp to keep clocks advancing on receive.
type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`        // sender's Lamport clock when sending reply
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"` // who sent this reply
	ToId          string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`       // (optional sanity/logging) intended recipient's node ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_ricartagrawala_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_ricartagrawala_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_ricartagrawala_proto_rawDescGZIP(), []int{2}
}

func (x *Reply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Reply) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Reply) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

var File_ricartagrawala_proto protoreflect.FileDescriptor

const file_ricartagrawala_proto_rawDesc = "" +
	"\n" +
	"\x14ricartagrawala.proto\x12\x02ra\"\a\n" +
	"\x05Empty\"@\n" +
	"\aRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\"S\n" +
	"\x05Reply\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId2S\n" +
	"\tRAService\x12#\n" +
	"\tRequestCS\x12\v.ra.Request\x1a\t.ra.Empty\x12!\n" +
	"\tSendReply\x12\t.ra.Reply\x1a\t.ra.EmptyB\x1cZ\x1aricartagrawala/proto;protob\x06proto3"

var (
	file_ricartagrawala_proto_rawDescOnce sync.Once
	file_ricartagrawala_proto_rawDescData []byte
)

func file_ricartagrawala_proto_rawDescGZIP() []byte {
	file_ricartagrawala_proto_rawDescOnce.Do(func() {
		file_ricartagrawala_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ricartagrawala_proto_rawDesc), len(file_ricartagrawala_proto_rawDesc)))
	})
	return file_ricartagrawala_proto_rawDescData
}

var file_ricartagrawala_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ricartagrawala_proto_goTypes = []any{
	(*Empty)(nil),   // 0: ra.Empty
	(*Request)(nil), // 1: ra.Request
	(*Reply)(nil),   // 2: ra.Reply
}
var file_ricartagrawala_proto_depIdxs = []int32{
	1, // 0: ra.RAService.RequestCS:input_type -> ra.Request
	2, // 1: ra.RAService.SendReply:input_type -> ra.Reply
	0, // 2: ra.RAService.RequestCS:output_type -> ra.Empty
	0, // 3: ra.RAService.SendReply:output_type -> ra.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ricartagrawala_proto_init() }
func file_ricartagrawala_proto_init() {
	if File_ricartagrawala_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ricartagrawala_proto_rawDesc), len(file_ricartagrawala_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ricartagrawala_proto_goTypes,
		DependencyIndexes: file_ricartagrawala_proto_depIdxs,
		MessageInfos:      file_ricartagrawala_proto_msgTypes,
	}.Build()
	File_ricartagrawala_proto = out.File
	file_ricartagrawala_proto_goTypes = nil
	file_ricartagrawala_proto_depIdxs = nil
}
